services:
  db:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - PGDATA="/var/lib/postgresql/data/pgdata"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U app -d app" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    
  server:
    image: mrtimego/calgon
    ports:
      - "5000:8080"
      - "5001:8081"
    environment: 
      CALGON_Infrastructure__ConnectionString: "Host=db;Username=app;Password=app;Database=app"
    depends_on:
      db:
        condition: service_healthy
    
volumes:
  db-data: