services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app

  pg-admin:
    image: dpage/pgadmin4
    ports:
      - "5001:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=app@example.com
      - PGADMIN_DEFAULT_PASSWORD=app
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
